# Generated by Django 5.1.5 on 2025-02-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_alter_adminsettings_access_control_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsettings',
            name='access_control',
            field=models.CharField(default='Set Permissions', max_length=100),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='notification_frequency',
            field=models.CharField(default='Instant', max_length=100),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='report_logs',
            field=models.CharField(default='Generate Reports', max_length=100),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='security_settings',
            field=models.CharField(default='Configure Policies', max_length=100),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='system_settings',
            field=models.CharField(default='Update Config', max_length=100),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='user_management',
            field=models.CharField(default='Manage Users', max_length=100),
        ),
    ]
