# Generated by Django 5.1.5 on 2025-02-12 07:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0007_alter_adminsettings_access_control_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='access_control',
            field=models.CharField(default='Set Permissions', max_length=255),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='notification_frequency',
            field=models.CharField(default='Instant', max_length=255),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='report_logs',
            field=models.CharField(default='Generate Reports', max_length=255),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='security_settings',
            field=models.CharField(default='Configure Policies', max_length=255),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='system_settings',
            field=models.CharField(default='Update Config', max_length=255),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='user_management',
            field=models.CharField(default='Manage Users', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
