# Generated by Django 5.1.5 on 2025-02-17 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0013_alter_userprofile_options_alter_userprofile_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('user_email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=255)),
                ('highest_score', models.FloatField()),
                ('time_taken', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TestSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('average_score', models.FloatField()),
                ('total_users', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('score', models.FloatField()),
                ('time_taken', models.CharField(max_length=50)),
                ('responses', models.JSONField()),
            ],
        ),
    ]
