# Generated by Django 5.1.5 on 2025-02-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0014_completedtest_testsummary_userresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsummary',
            name='median_score',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testsummary',
            name='pass_rate',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testsummary',
            name='total_attempts',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
