# Generated by Django 5.1.5 on 2025-02-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0015_testsummary_median_score_testsummary_pass_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedtest',
            name='time_taken',
            field=models.CharField(max_length=100),
        ),
    ]
