# Generated by Django 5.1.5 on 2025-02-18 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0018_rename_name_userresponse_test_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresponse',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='score',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='time_taken',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='user_name',
        ),
    ]
