# Generated by Django 5.1.5 on 2025-02-19 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0020_alter_completedtest_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedtest',
            name='user',
        ),
        migrations.AddField(
            model_name='completedtest',
            name='user_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='completedtest',
            name='user_name',
            field=models.CharField(default='Anonymous', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='completedtest',
            name='time_taken',
            field=models.DurationField(),
        ),
    ]
