# Generated by Django 5.1.5 on 2025-02-19 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0022_completedtest_user_alter_completedtest_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedtest',
            name='user',
        ),
    ]
