# Generated by Django 5.1.5 on 2025-02-19 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0024_completedtest_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedtest',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='completedtest',
            name='user_name',
        ),
        migrations.AlterField(
            model_name='completedtest',
            name='time_taken',
            field=models.CharField(max_length=100),
        ),
    ]
