# Generated by Django 5.1.5 on 2025-02-19 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0025_remove_completedtest_user_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='completedtest',
            options={'ordering': ['-highest_score'], 'verbose_name': 'Completed Test', 'verbose_name_plural': 'Completed Tests'},
        ),
        migrations.AlterField(
            model_name='completedtest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_tests', to=settings.AUTH_USER_MODEL),
        ),
    ]
