# Generated by Django 5.1.5 on 2025-02-19 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0026_alter_completedtest_options_alter_completedtest_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='completedtest',
            options={},
        ),
    ]
