# Generated by Django 5.1.5 on 2025-02-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0028_alter_completedtest_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedtest',
            name='user',
        ),
        migrations.AddField(
            model_name='completedtest',
            name='user_email',
            field=models.EmailField(default='default@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completedtest',
            name='user_name',
            field=models.CharField(default='Default User', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='completedtest',
            name='time_taken',
            field=models.CharField(max_length=50),
        ),
    ]
