# Generated by Django 5.1.5 on 2025-02-19 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0029_remove_completedtest_user_completedtest_user_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedtest',
            name='user_email',
        ),
        migrations.RemoveField(
            model_name='completedtest',
            name='user_name',
        ),
        migrations.AddField(
            model_name='completedtest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
