# Generated by Django 5.1.5 on 2025-02-19 09:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0030_remove_completedtest_user_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completedtest',
            name='title',
        ),
        migrations.AddField(
            model_name='completedtest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='completedtest',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='newapp.test'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='completedtest',
            name='highest_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='completedtest',
            name='time_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='completedtest',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
