# Generated by Django 5.1.5 on 2025-02-05 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_achievement_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboardrank',
            name='user',
        ),
        migrations.RemoveField(
            model_name='performancestat',
            name='user',
        ),
        migrations.DeleteModel(
            name='Achievement',
        ),
        migrations.DeleteModel(
            name='LeaderboardRank',
        ),
        migrations.DeleteModel(
            name='PerformanceStat',
        ),
    ]
