# Generated by Django 5.1.5 on 2025-02-11 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_remove_leaderboardrank_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dark_mode', models.BooleanField(default=False)),
                ('user_management', models.CharField(default='Manage Users', max_length=255)),
                ('access_control', models.CharField(default='Set Permissions', max_length=255)),
                ('system_settings', models.CharField(default='Update Config', max_length=255)),
                ('report_logs', models.CharField(default='Generate Reports', max_length=255)),
                ('security_settings', models.CharField(default='Configure Policies', max_length=255)),
                ('notification_frequency', models.CharField(default='Instant', max_length=255)),
                ('email_notifications', models.BooleanField(default=True)),
            ],
        ),
    ]
