# Generated by Django 5.1.5 on 2025-02-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_adminsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsettings',
            name='access_control',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='email_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='notification_frequency',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='report_logs',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='security_settings',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='system_settings',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='user_management',
            field=models.CharField(max_length=255),
        ),
    ]
