# Generated by Django 5.1.5 on 2025-02-21 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('average_score', models.FloatField()),
                ('total_users', models.IntegerField()),
                ('median_score', models.FloatField()),
                ('pass_rate', models.FloatField()),
                ('total_attempts', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='userresponse',
            old_name='score',
            new_name='attempts',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='responses',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='test',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='time_taken',
        ),
        migrations.RemoveField(
            model_name='userresponse',
            name='user',
        ),
        migrations.AddField(
            model_name='userresponse',
            name='correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='incorrect',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='question',
            field=models.TextField(default=False),
        ),
        migrations.AddField(
            model_name='userresponse',
            name='test_name',
            field=models.CharField(default=False, max_length=255),
        ),
        migrations.CreateModel(
            name='CompletedTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('highest_score', models.FloatField()),
                ('time_taken', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
