# Generated by Django 5.1.5 on 2025-02-21 07:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_leaderboardentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='achievement',
            name='date_earned',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='achievement',
            name='details',
            field=models.TextField(default='No details provided'),
        ),
        migrations.AddField(
            model_name='completedtest',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='completedtest',
            name='improvement',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='completedtest',
            name='name',
            field=models.CharField(default='Unnamed Test', max_length=255),
        ),
        migrations.AddField(
            model_name='completedtest',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='completedtest',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='completedtest',
            name='subject',
            field=models.CharField(default='maths', max_length=255),
        ),
        migrations.AddField(
            model_name='notification',
            name='details',
            field=models.TextField(default='No details provided'),
        ),
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(default='Untitled', max_length=255),
        ),
        migrations.AddField(
            model_name='performancestats',
            name='date_taken',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='performancestats',
            name='score',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='performancestats',
            name='subject',
            field=models.CharField(default='maths', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(default='No messages provided'),
        ),
        migrations.CreateModel(
            name='RecentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('details', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
