# Generated by Django 5.1.5 on 2025-02-24 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_date_notification_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='total_marks',
            field=models.IntegerField(default=100),
        ),
    ]
