# Generated by Django 5.1.5 on 2025-02-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_answer_question_id_answer_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='allow_blank_answers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='allow_jump_around',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='conclusion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='disable_autocomplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='disable_copy_paste',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='disable_printing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='disable_right_click',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='disable_spellcheck',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='disable_translate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='display_correct_answer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='due_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='indicate_correctness',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='move_on_without_feedback',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='notification_emails',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='only_move_forward',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='penalize_incorrect_answers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='randomize_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='receive_email_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='show_explanation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='show_score',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='show_test_outline',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
