# Generated by Django 5.1.5 on 2025-02-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_test_allow_blank_answers_test_allow_jump_around_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
