# Generated by Django 5.1.5 on 2025-02-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_test_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='test',
        ),
        migrations.RemoveField(
            model_name='test',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='test',
            name='date',
        ),
        migrations.RemoveField(
            model_name='test',
            name='is_auto_graded',
        ),
        migrations.AddField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(related_name='tests', to='blog.question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('truefalse', 'True/False'), ('multiplechoice', 'Multiple Choice'), ('multipleresponse', 'Multiple Response'), ('fillintheblank', 'Fill in the Blank')], max_length=20),
        ),
        migrations.AlterField(
            model_name='test',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
