# Generated by Django 5.1.5 on 2025-02-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_question_test_remove_test_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='correct_answer',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='options',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
