# Generated by Django 5.1.5 on 2025-02-26 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_question_correct_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='correct_answer',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
