# Generated by Django 5.1.5 on 2025-02-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_question_correct_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('multiplechoice', 'Multiple Choice'), ('multipleresponse', 'Multiple Response'), ('fillintheblanks', 'Fill in the Blanks'), ('truefalse', 'True/False')], max_length=20),
        ),
    ]
