# Generated by Django 5.1.5 on 2025-02-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_question_options_alter_question_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('multiplechoice', 'Multiple Choice'), ('multipleresponse', 'Multiple Response'), ('fillintheblank', 'Fill in the Blank'), ('truefalse', 'True/False')], max_length=20),
        ),
    ]
