# Generated by Django 5.1.5 on 2025-02-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='options',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
