# Generated by Django 5.1.5 on 2025-02-26 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_test_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='correct_answer',
        ),
    ]
