# Generated by Django 5.1.5 on 2025-02-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_remove_test_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='correct_answer',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
    ]
