# Generated by Django 5.1.5 on 2025-02-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_remove_test_correct_answer_remove_test_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='correct_answer',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='options',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='questions',
            field=models.ManyToManyField(related_name='tests', to='blog.question'),
        ),
    ]
