# Generated by Django 5.1.5 on 2025-02-27 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_learner_user_activitylog_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testresult',
            old_name='completed_at',
            new_name='completed',
        ),
    ]
