# Generated by Django 5.1.5 on 2025-02-27 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_remove_test_correct_answer_testresult_completed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='userToken',
        ),
    ]
