# Generated by Django 5.1.5 on 2025-02-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_remove_customuser_usertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='userToken',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
