# Generated by Django 5.1.5 on 2025-02-27 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_customuser_usertoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
