# Generated by Django 5.1.5 on 2025-03-04 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_delete_customuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='test',
            name='is_ongoing',
        ),
        migrations.RemoveField(
            model_name='test',
            name='options',
        ),
        migrations.RemoveField(
            model_name='test',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='test',
            name='test_type',
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='blog.test'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaderboardentry',
            name='badges',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('multiplechoice', 'Multiple Choice'), ('multipleresponse', 'Multiple Response'), ('truefalse', 'True/False'), ('fillintheblank', 'Fill in the Blank')], max_length=20),
        ),
        migrations.AlterField(
            model_name='test',
            name='category',
            field=models.CharField(choices=[('math', 'Math'), ('science', 'Science'), ('history', 'History'), ('literature', 'Literature'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='test',
            name='conclusion',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=50),
        ),
        migrations.AlterField(
            model_name='test',
            name='instructions',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='marks_per_question',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='test',
            name='notification_emails',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='pass_criteria',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='test',
            name='rank',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='test',
            name='status',
            field=models.CharField(default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='test',
            name='total_marks',
            field=models.IntegerField(),
        ),
    ]
