# Generated by Django 5.1.5 on 2025-03-05 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_remove_test_allow_feedback_remove_test_time_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='time_limit_per_question',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='test',
            name='total_time_limit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
