# Generated by Django 5.1.5 on 2025-03-05 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_alter_test_time_limit_per_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertoken',
            name='role',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
