# Generated by Django 5.1.5 on 2025-03-05 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_usertoken_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertoken',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
