# Generated by Django 5.1.6 on 2025-03-13 07:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_userprofile_attempted_tests_userprofile_rank_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='allow_blank_answers',
        ),
        migrations.RemoveField(
            model_name='test',
            name='allow_jump_around',
        ),
        migrations.RemoveField(
            model_name='test',
            name='disable_autocomplete',
        ),
        migrations.RemoveField(
            model_name='test',
            name='disable_copy_paste',
        ),
        migrations.RemoveField(
            model_name='test',
            name='disable_printing',
        ),
        migrations.RemoveField(
            model_name='test',
            name='disable_right_click',
        ),
        migrations.RemoveField(
            model_name='test',
            name='disable_spellcheck',
        ),
        migrations.RemoveField(
            model_name='test',
            name='disable_translate',
        ),
        migrations.RemoveField(
            model_name='test',
            name='display_correct_answer',
        ),
        migrations.RemoveField(
            model_name='test',
            name='indicate_correctness',
        ),
        migrations.RemoveField(
            model_name='test',
            name='is_timed',
        ),
        migrations.RemoveField(
            model_name='test',
            name='move_on_without_feedback',
        ),
        migrations.RemoveField(
            model_name='test',
            name='notification_emails',
        ),
        migrations.RemoveField(
            model_name='test',
            name='number_of_retakes',
        ),
        migrations.RemoveField(
            model_name='test',
            name='only_move_forward',
        ),
        migrations.RemoveField(
            model_name='test',
            name='penalize_incorrect_answers',
        ),
        migrations.RemoveField(
            model_name='test',
            name='randomize_order',
        ),
        migrations.RemoveField(
            model_name='test',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='test',
            name='receive_email_notifications',
        ),
        migrations.RemoveField(
            model_name='test',
            name='scheduled_date',
        ),
        migrations.RemoveField(
            model_name='test',
            name='show_explanation',
        ),
        migrations.RemoveField(
            model_name='test',
            name='show_score',
        ),
        migrations.RemoveField(
            model_name='test',
            name='show_test_outline',
        ),
        migrations.RemoveField(
            model_name='test',
            name='status',
        ),
        migrations.RemoveField(
            model_name='test',
            name='time_limit_per_question',
        ),
        migrations.RemoveField(
            model_name='test',
            name='total_time_limit',
        ),
        migrations.RemoveField(
            model_name='testattempt',
            name='can_reattempt',
        ),
        migrations.RemoveField(
            model_name='testattempt',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='testattempt',
            name='passed',
        ),
        migrations.RemoveField(
            model_name='testattempt',
            name='time_taken',
        ),
        migrations.AddField(
            model_name='test',
            name='allow_feedback',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='time_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testattempt',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], default='ongoing', max_length=10),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='question',
            name='options',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='blog.test'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('multiplechoice', 'Multiple Choice'), ('truefalse', 'True/False'), ('fillintheblank', 'Fill in the Blank'), ('multipleresponse', 'Multiple Response')], max_length=50),
        ),
        migrations.AlterField(
            model_name='test',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='test',
            name='conclusion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='marks_per_question',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='pass_criteria',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='subject',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='test',
            name='total_marks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.JSONField()),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='blog.testattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.question')),
            ],
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
