# Generated by Django 5.1.6 on 2025-03-18 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_testattempt_location_testattempt_microphone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_title', models.CharField(max_length=255)),
                ('attempted_test_id', models.CharField(max_length=255)),
                ('attempt_date', models.DateTimeField()),
                ('total_score', models.FloatField()),
                ('total_questions', models.IntegerField()),
                ('time_taken', models.DurationField()),
                ('passed', models.BooleanField()),
                ('can_reattempt', models.BooleanField()),
                ('answers', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
