# Generated by Django 5.1.6 on 2025-03-18 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_test_time_limit_per_question_test_total_questions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='performancehistory',
            old_name='user',
            new_name='username',
        ),
    ]
