# Generated by Django 5.1.6 on 2025-03-25 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0041_adminnotification_answer_contactmessage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attemptedtest',
            name='status',
            field=models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed')], default='ongoing', max_length=10),
        ),
    ]
