# Generated by Django 5.1.6 on 2025-03-25 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_alter_attemptedtest_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecentActivity',
        ),
    ]
