# Generated by Django 5.1.6 on 2025-03-25 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0045_customuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user',
        ),
    ]
