# Generated by Django 5.1.6 on 2025-04-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0049_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
