# Generated by Django 5.1.6 on 2025-04-08 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0050_alter_customuser_user_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_participants', to='blog.test')),
            ],
        ),
    ]
