# Generated by Django 5.1.6 on 2025-04-10 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0051_allowedparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='notification_emails',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='test',
            name='receive_email_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
