# Generated by Django 5.2 on 2025-04-28 14:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0055_alter_announcement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
