# Generated by Django 5.2 on 2025-05-05 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0056_test_test_uuid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentCapture',
        ),
    ]
