# Generated by Django 5.2 on 2025-05-05 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0060_alter_question_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='testuser',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.test'),
        ),
        migrations.AddField(
            model_name='testuser',
            name='token',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='testuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='testuser',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
