# Generated by Django 5.2 on 2025-05-06 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0061_testuser_test_testuser_token_alter_testuser_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testuser',
            name='test',
        ),
        migrations.RemoveField(
            model_name='testuser',
            name='token',
        ),
        migrations.AlterField(
            model_name='testuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='testuser',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
